name: Check Update

on:
  workflow_dispatch:
  schedule:
    - cron: '45 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: 'jdk'
      - name: Check update with
        run: ./java -jar build-cache/HMCL-Snapshot-Update-Checker.jar
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "[BOT] Update version json."